# Generated by Django 4.0.5 on 2022-06-06 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_actor_picture'),
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(related_name='actor', to='actor.actor', verbose_name='Actor Name'),
        ),
    ]
