# Generated by Django 4.0.5 on 2022-06-07 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0001_initial'),
        ('movie', '0002_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='director.director', verbose_name='Director Name'),
        ),
    ]
