# Generated by Django 4.0.5 on 2022-06-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
        ('movie', '0003_alter_movie_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(to='actor.actor', verbose_name='Actor Name'),
        ),
    ]
