# Generated by Django 4.0.5 on 2022-06-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0002_actor_birth_date'),
        ('movie', '0004_alter_movie_actor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='actor',
            field=models.ManyToManyField(to='actor.actor'),
        ),
    ]
