# Generated by Django 4.0.5 on 2022-06-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(null=True, upload_to='actor'),
        ),
    ]
