# Generated by Django 4.0.5 on 2022-06-05 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0003_alter_actor_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='picture',
        ),
    ]
