# Generated by Django 4.0.5 on 2022-06-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0004_remove_actor_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='actor'),
        ),
    ]
