# Generated by Django 4.0.5 on 2022-06-06 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actor', '0005_actor_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='picture',
            field=models.ImageField(default=' ', upload_to='actor'),
            preserve_default=False,
        ),
    ]
